-- ============================================================================
-- ENUM → VARCHAR Migration
-- Date: 2026-03-08
-- Purpose: Convert all ENUM columns to VARCHAR with COMMENT listing valid values
-- Scope: All AHG plugin base tables in archive database (459 columns)
-- Rule: "Never use ENUM columns" — use VARCHAR(N) with COMMENT instead
-- Note: Views (grap_heritage_asset, ric_queue_status, ric_recent_operations,
--        ric_sync_summary) are excluded — they inherit column types from base tables
-- ============================================================================

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET CHARACTER SET utf8mb4;

ALTER TABLE `heritage_access_request` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'pending' COMMENT 'pending, approved, denied, expired, withdrawn';
ALTER TABLE `heritage_access_rule` MODIFY COLUMN `action` VARCHAR(63) DEFAULT 'view' COMMENT 'view, view_metadata, download, download_master, print, all';
ALTER TABLE `heritage_access_rule` MODIFY COLUMN `applies_to` VARCHAR(49) DEFAULT 'all' COMMENT 'all, anonymous, authenticated, trust_level';
ALTER TABLE `heritage_access_rule` MODIFY COLUMN `rule_type` VARCHAR(37) DEFAULT 'deny' COMMENT 'allow, deny, require_approval';
ALTER TABLE `heritage_analytics_alert` MODIFY COLUMN `category` VARCHAR(58) DEFAULT 'system' COMMENT 'content, search, access, quality, system, opportunity';
ALTER TABLE `heritage_analytics_alert` MODIFY COLUMN `severity` VARCHAR(39) DEFAULT 'info' COMMENT 'info, warning, critical, success';
ALTER TABLE `heritage_asset` MODIFY COLUMN `acquisition_method` VARCHAR(65) DEFAULT NULL COMMENT 'purchase, donation, bequest, transfer, found, exchange, other';
ALTER TABLE `heritage_asset` MODIFY COLUMN `condition_rating` VARCHAR(43) DEFAULT NULL COMMENT 'excellent, good, fair, poor, critical';
ALTER TABLE `heritage_asset` MODIFY COLUMN `depreciation_policy` VARCHAR(76) DEFAULT 'not_depreciated' COMMENT 'not_depreciated, straight_line, reducing_balance, units_of_production';
ALTER TABLE `heritage_asset` MODIFY COLUMN `derecognition_reason` VARCHAR(60) DEFAULT NULL COMMENT 'disposal, destruction, loss, transfer, write_off, other';
ALTER TABLE `heritage_asset` MODIFY COLUMN `heritage_significance` VARCHAR(37) DEFAULT NULL COMMENT 'exceptional, high, medium, low';
ALTER TABLE `heritage_asset` MODIFY COLUMN `measurement_basis` VARCHAR(49) DEFAULT 'cost' COMMENT 'cost, fair_value, nominal, not_practicable';
ALTER TABLE `heritage_asset` MODIFY COLUMN `recognition_status` VARCHAR(56) DEFAULT 'pending' COMMENT 'recognised, not_recognised, pending, derecognised';
ALTER TABLE `heritage_asset` MODIFY COLUMN `revaluation_frequency` VARCHAR(64) DEFAULT 'as_needed' COMMENT 'annual, triennial, quinquennial, as_needed, not_applicable';
ALTER TABLE `heritage_asset` MODIFY COLUMN `valuation_method` VARCHAR(51) DEFAULT NULL COMMENT 'market, cost, income, expert, insurance, other';
ALTER TABLE `heritage_audit_log` MODIFY COLUMN `action_category` VARCHAR(69) DEFAULT 'update' COMMENT 'create, update, delete, view, export, import, batch, access, system';
ALTER TABLE `heritage_batch_item` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'pending' COMMENT 'pending, processing, success, failed, skipped';
ALTER TABLE `heritage_batch_job` MODIFY COLUMN `status` VARCHAR(69) DEFAULT 'pending' COMMENT 'pending, queued, processing, completed, failed, cancelled, paused';
ALTER TABLE `heritage_compliance_rule` MODIFY COLUMN `category` VARCHAR(44) NOT NULL COMMENT 'recognition, measurement, disclosure';
ALTER TABLE `heritage_compliance_rule` MODIFY COLUMN `check_type` VARCHAR(54) DEFAULT 'required_field' COMMENT 'required_field, value_check, date_check, custom';
ALTER TABLE `heritage_compliance_rule` MODIFY COLUMN `severity` VARCHAR(28) DEFAULT 'error' COMMENT 'error, warning, info';
ALTER TABLE `heritage_contribution` MODIFY COLUMN `status` VARCHAR(46) DEFAULT 'pending' COMMENT 'pending, approved, rejected, superseded';
ALTER TABLE `heritage_contribution_type` MODIFY COLUMN `min_trust_level` VARCHAR(40) DEFAULT 'new' COMMENT 'new, contributor, trusted, expert';
ALTER TABLE `heritage_contributor` MODIFY COLUMN `trust_level` VARCHAR(40) DEFAULT 'new' COMMENT 'new, contributor, trusted, expert';
ALTER TABLE `heritage_contributor_badge` MODIFY COLUMN `criteria_type` VARCHAR(70) DEFAULT 'contribution_count' COMMENT 'contribution_count, approval_rate, points, type_specific, manual';
ALTER TABLE `heritage_curated_story` MODIFY COLUMN `link_type` VARCHAR(41) DEFAULT 'search' COMMENT 'collection, search, external, page';
ALTER TABLE `heritage_embargo` MODIFY COLUMN `embargo_type` VARCHAR(43) DEFAULT 'full' COMMENT 'full, digital_only, metadata_hidden';
ALTER TABLE `heritage_explore_category` MODIFY COLUMN `display_style` VARCHAR(41) DEFAULT 'grid' COMMENT 'grid, list, timeline, map, carousel';
ALTER TABLE `heritage_explore_category` MODIFY COLUMN `source_type` VARCHAR(47) NOT NULL COMMENT 'taxonomy, authority, field, facet, custom';
ALTER TABLE `heritage_featured_collection` MODIFY COLUMN `source_type` VARCHAR(23) NOT NULL DEFAULT 'archival' COMMENT 'iiif, archival';
ALTER TABLE `heritage_filter_type` MODIFY COLUMN `source_type` VARCHAR(41) NOT NULL COMMENT 'taxonomy, authority, field, custom';
ALTER TABLE `heritage_graph_build_log` MODIFY COLUMN `build_type` VARCHAR(37) NOT NULL DEFAULT 'incremental' COMMENT 'full, incremental, edges_only';
ALTER TABLE `heritage_graph_build_log` MODIFY COLUMN `status` VARCHAR(34) NOT NULL DEFAULT 'running' COMMENT 'running, completed, failed';
ALTER TABLE `heritage_hero_slide` MODIFY COLUMN `cta_style` VARCHAR(41) DEFAULT 'primary' COMMENT 'primary, secondary, outline, light';
ALTER TABLE `heritage_hero_slide` MODIFY COLUMN `media_type` VARCHAR(21) DEFAULT 'image' COMMENT 'image, video';
ALTER TABLE `heritage_hero_slide` MODIFY COLUMN `overlay_type` VARCHAR(29) DEFAULT 'gradient' COMMENT 'none, gradient, solid';
ALTER TABLE `heritage_hero_slide` MODIFY COLUMN `text_position` VARCHAR(52) DEFAULT 'left' COMMENT 'left, center, right, bottom-left, bottom-right';
ALTER TABLE `heritage_journal_entry` MODIFY COLUMN `journal_type` VARCHAR(111) NOT NULL COMMENT 'recognition, revaluation, depreciation, impairment, impairment_reversal, derecognition, adjustment, transfer';
ALTER TABLE `heritage_landing_config` MODIFY COLUMN `hero_effect` VARCHAR(28) DEFAULT 'kenburns' COMMENT 'kenburns, fade, none';
ALTER TABLE `heritage_learned_term` MODIFY COLUMN `relationship_type` VARCHAR(51) DEFAULT 'related' COMMENT 'synonym, broader, narrower, related, spelling';
ALTER TABLE `heritage_learned_term` MODIFY COLUMN `source` VARCHAR(47) DEFAULT 'user_behavior' COMMENT 'user_behavior, admin, taxonomy, external';
ALTER TABLE `heritage_movement_register` MODIFY COLUMN `condition_on_departure` VARCHAR(34) DEFAULT NULL COMMENT 'excellent, good, fair, poor';
ALTER TABLE `heritage_movement_register` MODIFY COLUMN `condition_on_return` VARCHAR(34) DEFAULT NULL COMMENT 'excellent, good, fair, poor';
ALTER TABLE `heritage_movement_register` MODIFY COLUMN `movement_type` VARCHAR(84) NOT NULL COMMENT 'loan_out, loan_return, transfer, exhibition, conservation, storage_change, other';
ALTER TABLE `heritage_popia_flag` MODIFY COLUMN `detected_by` VARCHAR(33) DEFAULT 'manual' COMMENT 'automatic, manual, review';
ALTER TABLE `heritage_popia_flag` MODIFY COLUMN `flag_type` VARCHAR(105) NOT NULL COMMENT 'personal_info, sensitive, children, health, biometric, criminal, financial, political, religious, sexual';
ALTER TABLE `heritage_popia_flag` MODIFY COLUMN `severity` VARCHAR(34) DEFAULT 'medium' COMMENT 'low, medium, high, critical';
ALTER TABLE `heritage_search_suggestion` MODIFY COLUMN `suggestion_type` VARCHAR(43) DEFAULT 'query' COMMENT 'query, title, subject, creator, place';
ALTER TABLE `heritage_tenant` MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'trial' COMMENT 'active, suspended, trial';
ALTER TABLE `heritage_tenant_user` MODIFY COLUMN `role` VARCHAR(52) NOT NULL DEFAULT 'viewer' COMMENT 'owner, super_user, editor, contributor, viewer';
ALTER TABLE `heritage_valuation_history` MODIFY COLUMN `valuation_method` VARCHAR(51) DEFAULT NULL COMMENT 'market, cost, income, expert, insurance, other';
ALTER TABLE `icip_access_restriction` MODIFY COLUMN `restriction_type` VARCHAR(198) NOT NULL COMMENT 'community_permission_required, gender_restricted_male, gender_restricted_female, initiated_only, seasonal, mourning_period, repatriation_pending, under_consultation, elder_approval_required, custom';
ALTER TABLE `icip_community` MODIFY COLUMN `state_territory` VARCHAR(47) NOT NULL COMMENT 'NSW, VIC, QLD, WA, SA, TAS, NT, ACT, External';
ALTER TABLE `icip_consent` MODIFY COLUMN `consent_status` VARCHAR(135) NOT NULL DEFAULT 'unknown' COMMENT 'not_required, pending_consultation, consultation_in_progress, conditional_consent, full_consent, restricted_consent, denied, unknown';
ALTER TABLE `icip_consultation` MODIFY COLUMN `consultation_method` VARCHAR(50) NOT NULL COMMENT 'in_person, phone, video, email, letter, other';
ALTER TABLE `icip_consultation` MODIFY COLUMN `consultation_type` VARCHAR(132) NOT NULL COMMENT 'initial_contact, consent_request, access_request, repatriation, digitisation, exhibition, publication, research, general, follow_up';
ALTER TABLE `icip_consultation` MODIFY COLUMN `status` VARCHAR(58) NOT NULL DEFAULT 'completed' COMMENT 'scheduled, completed, cancelled, follow_up_required';
ALTER TABLE `icip_cultural_notice_type` MODIFY COLUMN `severity` VARCHAR(31) DEFAULT 'warning' COMMENT 'info, warning, critical';
ALTER TABLE `icip_tk_label` MODIFY COLUMN `applied_by` VARCHAR(31) NOT NULL DEFAULT 'institution' COMMENT 'community, institution';
ALTER TABLE `icip_tk_label_type` MODIFY COLUMN `category` VARCHAR(20) NOT NULL COMMENT 'TK, BC';
ALTER TABLE `iiif_annotation` MODIFY COLUMN `motivation` VARCHAR(86) DEFAULT 'commenting' COMMENT 'commenting, tagging, describing, linking, transcribing, identifying, supplementing';
ALTER TABLE `iiif_auth_access_log` MODIFY COLUMN `action` VARCHAR(67) NOT NULL COMMENT 'view, download, token_request, token_grant, token_deny, logout';
ALTER TABLE `iiif_auth_service` MODIFY COLUMN `profile` VARCHAR(43) NOT NULL DEFAULT 'login' COMMENT 'login, clickthrough, kiosk, external';
ALTER TABLE `iiif_collection` MODIFY COLUMN `viewing_hint` VARCHAR(53) DEFAULT 'individuals' COMMENT 'individuals, paged, continuous, multi-part, top';
ALTER TABLE `iiif_collection_item` MODIFY COLUMN `item_type` VARCHAR(29) DEFAULT 'manifest' COMMENT 'manifest, collection';
ALTER TABLE `iiif_ocr_block` MODIFY COLUMN `block_type` VARCHAR(36) DEFAULT 'word' COMMENT 'word, line, paragraph, region';
ALTER TABLE `iiif_ocr_text` MODIFY COLUMN `format` VARCHAR(25) DEFAULT 'plain' COMMENT 'plain, alto, hocr';
ALTER TABLE `information_object_physical_location` MODIFY COLUMN `access_status` VARCHAR(53) DEFAULT 'available' COMMENT 'available, in_use, restricted, offsite, missing';
ALTER TABLE `information_object_physical_location` MODIFY COLUMN `condition_status` VARCHAR(43) DEFAULT NULL COMMENT 'excellent, good, fair, poor, critical';
ALTER TABLE `ingest_file` MODIFY COLUMN `file_type` VARCHAR(31) NOT NULL COMMENT 'csv, zip, ead, directory';
ALTER TABLE `ingest_job` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'queued' COMMENT 'queued, running, completed, failed, cancelled';
ALTER TABLE `ingest_session` MODIFY COLUMN `parent_placement` VARCHAR(46) DEFAULT 'top_level' COMMENT 'existing, new, top_level, csv_hierarchy';
ALTER TABLE `ingest_session` MODIFY COLUMN `sector` VARCHAR(44) NOT NULL DEFAULT 'archive' COMMENT 'archive, museum, library, gallery, dam';
ALTER TABLE `ingest_session` MODIFY COLUMN `standard` VARCHAR(40) NOT NULL DEFAULT 'isadg' COMMENT 'isadg, dc, spectrum, cco, rad, dacs';
ALTER TABLE `ingest_session` MODIFY COLUMN `status` VARCHAR(81) DEFAULT 'configure' COMMENT 'configure, upload, map, validate, preview, commit, completed, failed, cancelled';
ALTER TABLE `ingest_validation` MODIFY COLUMN `severity` VARCHAR(28) DEFAULT 'error' COMMENT 'error, warning, info';
ALTER TABLE `ipsas_asset_category` MODIFY COLUMN `asset_type` VARCHAR(36) DEFAULT 'heritage' COMMENT 'heritage, operational, mixed';
ALTER TABLE `ipsas_asset_category` MODIFY COLUMN `depreciation_policy` VARCHAR(45) DEFAULT 'none' COMMENT 'none, straight_line, reducing_balance';
ALTER TABLE `ipsas_depreciation` MODIFY COLUMN `calculation_method` VARCHAR(40) NOT NULL COMMENT 'straight_line, reducing_balance';
ALTER TABLE `ipsas_disposal` MODIFY COLUMN `disposal_method` VARCHAR(67) NOT NULL COMMENT 'sale, donation, destruction, loss, theft, transfer, deaccession';
ALTER TABLE `ipsas_financial_year_summary` MODIFY COLUMN `status` VARCHAR(29) DEFAULT 'open' COMMENT 'open, closed, audited';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `acquisition_method` VARCHAR(67) DEFAULT 'unknown' COMMENT 'purchase, donation, bequest, transfer, found, exchange, unknown';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `condition_rating` VARCHAR(43) DEFAULT 'good' COMMENT 'excellent, good, fair, poor, critical';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `depreciation_policy` VARCHAR(45) DEFAULT 'none' COMMENT 'none, straight_line, reducing_balance';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `risk_level` VARCHAR(34) DEFAULT 'low' COMMENT 'low, medium, high, critical';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `status` VARCHAR(78) DEFAULT 'active' COMMENT 'active, on_loan, in_storage, under_conservation, disposed, lost, destroyed';
ALTER TABLE `ipsas_heritage_asset` MODIFY COLUMN `valuation_basis` VARCHAR(59) DEFAULT 'nominal' COMMENT 'historical_cost, fair_value, nominal, not_recognized';
ALTER TABLE `ipsas_insurance` MODIFY COLUMN `policy_type` VARCHAR(59) NOT NULL COMMENT 'all_risks, named_perils, blanket, transit, exhibition';
ALTER TABLE `ipsas_insurance` MODIFY COLUMN `status` VARCHAR(50) DEFAULT 'active' COMMENT 'active, expired, cancelled, pending_renewal';
ALTER TABLE `ipsas_valuation` MODIFY COLUMN `valuation_basis` VARCHAR(61) NOT NULL COMMENT 'historical_cost, fair_value, nominal, replacement_cost';
ALTER TABLE `ipsas_valuation` MODIFY COLUMN `valuation_type` VARCHAR(58) NOT NULL COMMENT 'initial, revaluation, impairment, reversal, disposal';
ALTER TABLE `ipsas_valuation` MODIFY COLUMN `valuer_type` VARCHAR(38) DEFAULT 'internal' COMMENT 'internal, external, government';
ALTER TABLE `library_settings` MODIFY COLUMN `setting_type` VARCHAR(37) DEFAULT 'string' COMMENT 'string, integer, boolean, json';
ALTER TABLE `library_subject_authority` MODIFY COLUMN `heading_type` VARCHAR(61) DEFAULT 'topical' COMMENT 'topical, personal, corporate, geographic, genre, meeting';
ALTER TABLE `loan` MODIFY COLUMN `insurance_type` VARCHAR(48) NOT NULL DEFAULT 'borrower' COMMENT 'borrower, lender, shared, government, self';
ALTER TABLE `loan` MODIFY COLUMN `loan_type` VARCHAR(20) NOT NULL COMMENT 'out, in';
ALTER TABLE `loan` MODIFY COLUMN `purpose` VARCHAR(88) NOT NULL DEFAULT 'exhibition' COMMENT 'exhibition, research, conservation, photography, education, filming, long_term, other';
ALTER TABLE `loan_document` MODIFY COLUMN `document_type` VARCHAR(116) NOT NULL COMMENT 'agreement, facilities_report, condition_report, insurance_certificate, receipt, correspondence, photograph, other';
ALTER TABLE `marketplace_auction` MODIFY COLUMN `auction_type` VARCHAR(34) DEFAULT 'english' COMMENT 'english, sealed_bid, dutch';
ALTER TABLE `marketplace_auction` MODIFY COLUMN `status` VARCHAR(41) DEFAULT 'upcoming' COMMENT 'upcoming, active, ended, cancelled';
ALTER TABLE `marketplace_category` MODIFY COLUMN `sector` VARCHAR(44) NOT NULL COMMENT 'gallery, museum, archive, library, dam';
ALTER TABLE `marketplace_collection` MODIFY COLUMN `collection_type` VARCHAR(57) DEFAULT 'curated' COMMENT 'curated, exhibition, seasonal, featured, genre, sale';
ALTER TABLE `marketplace_enquiry` MODIFY COLUMN `status` VARCHAR(33) DEFAULT 'new' COMMENT 'new, read, replied, closed';
ALTER TABLE `marketplace_listing` MODIFY COLUMN `condition_rating` VARCHAR(39) DEFAULT NULL COMMENT 'mint, excellent, good, fair, poor';
ALTER TABLE `marketplace_listing` MODIFY COLUMN `listing_type` VARCHAR(40) NOT NULL COMMENT 'fixed_price, auction, offer_only';
ALTER TABLE `marketplace_listing` MODIFY COLUMN `sector` VARCHAR(44) NOT NULL COMMENT 'gallery, museum, archive, library, dam';
ALTER TABLE `marketplace_listing` MODIFY COLUMN `status` VARCHAR(79) DEFAULT 'draft' COMMENT 'draft, pending_review, active, reserved, sold, expired, withdrawn, suspended';
ALTER TABLE `marketplace_offer` MODIFY COLUMN `status` VARCHAR(63) DEFAULT 'pending' COMMENT 'pending, accepted, rejected, countered, withdrawn, expired';
ALTER TABLE `marketplace_payout` MODIFY COLUMN `method` VARCHAR(60) NOT NULL COMMENT 'bank_transfer, paypal, payfast, manual, stripe_connect';
ALTER TABLE `marketplace_payout` MODIFY COLUMN `status` VARCHAR(55) DEFAULT 'pending' COMMENT 'pending, processing, completed, failed, cancelled';
ALTER TABLE `marketplace_review` MODIFY COLUMN `review_type` VARCHAR(41) NOT NULL COMMENT 'buyer_to_seller, seller_to_buyer';
ALTER TABLE `marketplace_seller` MODIFY COLUMN `payout_method` VARCHAR(45) DEFAULT 'bank_transfer' COMMENT 'bank_transfer, paypal, payfast, manual';
ALTER TABLE `marketplace_seller` MODIFY COLUMN `seller_type` VARCHAR(53) NOT NULL COMMENT 'artist, gallery, institution, collector, estate';
ALTER TABLE `marketplace_seller` MODIFY COLUMN `trust_level` VARCHAR(36) DEFAULT 'new' COMMENT 'new, active, trusted, premium';
ALTER TABLE `marketplace_seller` MODIFY COLUMN `verification_status` VARCHAR(47) DEFAULT 'unverified' COMMENT 'unverified, pending, verified, suspended';
ALTER TABLE `marketplace_settings` MODIFY COLUMN `setting_type` VARCHAR(43) DEFAULT 'text' COMMENT 'text, number, boolean, json, currency';
ALTER TABLE `marketplace_transaction` MODIFY COLUMN `payment_status` VARCHAR(47) DEFAULT 'pending' COMMENT 'pending, paid, failed, refunded, disputed';
ALTER TABLE `marketplace_transaction` MODIFY COLUMN `shipping_status` VARCHAR(65) DEFAULT 'pending' COMMENT 'pending, preparing, shipped, in_transit, delivered, returned';
ALTER TABLE `marketplace_transaction` MODIFY COLUMN `source` VARCHAR(35) NOT NULL COMMENT 'fixed_price, auction, offer';
ALTER TABLE `marketplace_transaction` MODIFY COLUMN `status` VARCHAR(87) DEFAULT 'pending_payment' COMMENT 'pending_payment, paid, shipping, delivered, completed, cancelled, disputed, refunded';
ALTER TABLE `media_derivatives` MODIFY COLUMN `derivative_type` VARCHAR(43) NOT NULL COMMENT 'thumbnail, poster, preview, waveform';
ALTER TABLE `media_metadata` MODIFY COLUMN `media_type` VARCHAR(21) NOT NULL COMMENT 'audio, video';
ALTER TABLE `media_processing_queue` MODIFY COLUMN `status` VARCHAR(45) DEFAULT 'pending' COMMENT 'pending, processing, completed, failed';
ALTER TABLE `media_processing_queue` MODIFY COLUMN `task_type` VARCHAR(62) NOT NULL COMMENT 'metadata_extraction, transcription, waveform, thumbnail';
ALTER TABLE `media_processor_settings` MODIFY COLUMN `setting_type` VARCHAR(43) DEFAULT 'string' COMMENT 'string, integer, float, boolean, json';
ALTER TABLE `metadata_export_log` MODIFY COLUMN `status` VARCHAR(32) DEFAULT 'success' COMMENT 'success, failed, partial';
ALTER TABLE `metadata_extraction_log` MODIFY COLUMN `operation` VARCHAR(56) NOT NULL COMMENT 'extract, face_detect, face_match, index_face, bulk';
ALTER TABLE `metadata_extraction_log` MODIFY COLUMN `status` VARCHAR(40) NOT NULL COMMENT 'success, partial, failed, skipped';
ALTER TABLE `metadata_extraction_log` MODIFY COLUMN `triggered_by` VARCHAR(31) DEFAULT NULL COMMENT 'upload, job, manual, api';
ALTER TABLE `naz_closure_period` MODIFY COLUMN `closure_type` VARCHAR(50) NOT NULL DEFAULT 'standard' COMMENT 'standard, extended, indefinite, ministerial';
ALTER TABLE `naz_closure_period` MODIFY COLUMN `status` VARCHAR(42) DEFAULT 'active' COMMENT 'active, expired, extended, released';
ALTER TABLE `naz_protected_record` MODIFY COLUMN `protection_type` VARCHAR(52) NOT NULL COMMENT 'cabinet, security, personal, legal, commercial';
ALTER TABLE `naz_protected_record` MODIFY COLUMN `status` VARCHAR(31) DEFAULT 'active' COMMENT 'active, expired, lifted';
ALTER TABLE `naz_records_schedule` MODIFY COLUMN `access_restriction` VARCHAR(45) DEFAULT 'open' COMMENT 'open, restricted, confidential, secret';
ALTER TABLE `naz_records_schedule` MODIFY COLUMN `classification` VARCHAR(46) DEFAULT 'useful' COMMENT 'vital, important, useful, non-essential';
ALTER TABLE `naz_records_schedule` MODIFY COLUMN `disposal_action` VARCHAR(43) NOT NULL COMMENT 'destroy, transfer, review, permanent';
ALTER TABLE `naz_records_schedule` MODIFY COLUMN `status` VARCHAR(52) DEFAULT 'draft' COMMENT 'draft, pending, approved, superseded, archived';
ALTER TABLE `naz_research_permit` MODIFY COLUMN `permit_type` VARCHAR(36) NOT NULL DEFAULT 'general' COMMENT 'general, restricted, special';
ALTER TABLE `naz_research_permit` MODIFY COLUMN `status` VARCHAR(58) DEFAULT 'pending' COMMENT 'pending, approved, rejected, active, expired, revoked';
ALTER TABLE `naz_researcher` MODIFY COLUMN `researcher_type` VARCHAR(37) NOT NULL DEFAULT 'local' COMMENT 'local, foreign, institutional';
ALTER TABLE `naz_researcher` MODIFY COLUMN `status` VARCHAR(47) DEFAULT 'active' COMMENT 'active, inactive, suspended, blacklisted';
ALTER TABLE `naz_transfer` MODIFY COLUMN `status` VARCHAR(79) DEFAULT 'proposed' COMMENT 'proposed, scheduled, in_transit, received, accessioned, rejected, cancelled';
ALTER TABLE `naz_transfer` MODIFY COLUMN `transfer_type` VARCHAR(45) DEFAULT 'scheduled' COMMENT 'scheduled, voluntary, rescue, donation';
ALTER TABLE `naz_transfer_item` MODIFY COLUMN `access_restriction` VARCHAR(38) DEFAULT 'open' COMMENT 'open, restricted, confidential';
ALTER TABLE `nmmz_antiquity` MODIFY COLUMN `acquisition_method` VARCHAR(68) DEFAULT 'unknown' COMMENT 'excavation, donation, purchase, confiscation, transfer, unknown';
ALTER TABLE `nmmz_antiquity` MODIFY COLUMN `condition_rating` VARCHAR(46) DEFAULT 'good' COMMENT 'excellent, good, fair, poor, fragmentary';
ALTER TABLE `nmmz_antiquity` MODIFY COLUMN `ownership_type` VARCHAR(38) DEFAULT 'state' COMMENT 'state, museum, private, unknown';
ALTER TABLE `nmmz_antiquity` MODIFY COLUMN `status` VARCHAR(61) DEFAULT 'in_collection' COMMENT 'in_collection, on_loan, missing, repatriated, destroyed';
ALTER TABLE `nmmz_archaeological_site` MODIFY COLUMN `protection_status` VARCHAR(49) DEFAULT 'unprotected' COMMENT 'protected, unprotected, at_risk, destroyed';
ALTER TABLE `nmmz_archaeological_site` MODIFY COLUMN `research_potential` VARCHAR(35) DEFAULT 'medium' COMMENT 'high, medium, low, exhausted';
ALTER TABLE `nmmz_archaeological_site` MODIFY COLUMN `status` VARCHAR(47) DEFAULT 'active' COMMENT 'active, destroyed, submerged, built_over';
ALTER TABLE `nmmz_export_permit` MODIFY COLUMN `applicant_type` VARCHAR(50) NOT NULL COMMENT 'individual, institution, dealer, researcher';
ALTER TABLE `nmmz_export_permit` MODIFY COLUMN `export_purpose` VARCHAR(63) NOT NULL COMMENT 'exhibition, research, conservation, sale, personal, return';
ALTER TABLE `nmmz_export_permit` MODIFY COLUMN `status` VARCHAR(65) DEFAULT 'pending' COMMENT 'pending, approved, rejected, issued, used, expired, cancelled';
ALTER TABLE `nmmz_heritage_impact_assessment` MODIFY COLUMN `impact_level` VARCHAR(39) DEFAULT 'moderate' COMMENT 'none, low, moderate, high, severe';
ALTER TABLE `nmmz_heritage_impact_assessment` MODIFY COLUMN `recommendation` VARCHAR(62) DEFAULT 'further_study' COMMENT 'approve, approve_with_conditions, reject, further_study';
ALTER TABLE `nmmz_heritage_impact_assessment` MODIFY COLUMN `status` VARCHAR(58) DEFAULT 'submitted' COMMENT 'submitted, under_review, approved, rejected, expired';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `condition_rating` VARCHAR(53) DEFAULT 'good' COMMENT 'excellent, good, fair, poor, critical, destroyed';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `conservation_priority` VARCHAR(25) DEFAULT 'medium' COMMENT 'high, medium, low';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `legal_status` VARCHAR(48) DEFAULT 'proposed' COMMENT 'gazetted, provisional, proposed, delisted';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `ownership_type` VARCHAR(38) DEFAULT 'state' COMMENT 'state, private, communal, mixed';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `protection_level` VARCHAR(35) DEFAULT 'national' COMMENT 'national, provincial, local';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `status` VARCHAR(43) DEFAULT 'active' COMMENT 'active, at_risk, destroyed, delisted';
ALTER TABLE `nmmz_monument` MODIFY COLUMN `world_heritage_status` VARCHAR(34) DEFAULT 'none' COMMENT 'inscribed, tentative, none';
ALTER TABLE `nmmz_monument_category` MODIFY COLUMN `protection_level` VARCHAR(35) DEFAULT 'national' COMMENT 'national, provincial, local';
ALTER TABLE `nmmz_monument_inspection` MODIFY COLUMN `condition_rating` VARCHAR(53) NOT NULL COMMENT 'excellent, good, fair, poor, critical, destroyed';
ALTER TABLE `nmmz_monument_inspection` MODIFY COLUMN `previous_rating` VARCHAR(53) DEFAULT NULL COMMENT 'excellent, good, fair, poor, critical, destroyed';
ALTER TABLE `numbering_scheme` MODIFY COLUMN `sector` VARCHAR(48) NOT NULL COMMENT 'archive, library, museum, gallery, dam, all';
ALTER TABLE `numbering_scheme` MODIFY COLUMN `sequence_reset` VARCHAR(30) DEFAULT 'never' COMMENT 'never, yearly, monthly';
ALTER TABLE `oais_fixity_check` MODIFY COLUMN `check_type` VARCHAR(27) NOT NULL COMMENT 'md5, sha256, sha512';
ALTER TABLE `oais_information_package` MODIFY COLUMN `package_type` VARCHAR(21) NOT NULL COMMENT 'SIP, AIP, DIP';
ALTER TABLE `oais_information_package` MODIFY COLUMN `preservation_level` VARCHAR(30) DEFAULT 'bit' COMMENT 'bit, logical, semantic';
ALTER TABLE `oais_information_package` MODIFY COLUMN `status` VARCHAR(63) DEFAULT 'pending' COMMENT 'pending, ingesting, stored, preserved, disseminated, error';
ALTER TABLE `oais_package_content` MODIFY COLUMN `content_type` VARCHAR(45) DEFAULT 'content' COMMENT 'content, metadata, manifest, signature';
ALTER TABLE `oais_premis_event` MODIFY COLUMN `event_outcome` VARCHAR(33) NOT NULL COMMENT 'success, failure, warning';
ALTER TABLE `oais_premis_event` MODIFY COLUMN `event_type` VARCHAR(269) NOT NULL COMMENT 'capture, compression, creation, deaccession, decompression, decryption, deletion, digital_signature_validation, dissemination, encryption, fixity_check, format_identification, ingestion, message_digest_calculation, migration, normalization, replication, validation, virus_check';
ALTER TABLE `oais_preservation_policy` MODIFY COLUMN `action_type` VARCHAR(44) NOT NULL COMMENT 'migrate, normalize, emulate, preserve';
ALTER TABLE `oais_pronom_format` MODIFY COLUMN `risk_level` VARCHAR(34) DEFAULT 'low' COMMENT 'low, medium, high, critical';
ALTER TABLE `object_3d_audit_log` MODIFY COLUMN `action` VARCHAR(79) NOT NULL COMMENT 'upload, update, delete, view, ar_view, download, hotspot_add, hotspot_delete';
ALTER TABLE `object_3d_hotspot` MODIFY COLUMN `hotspot_type` VARCHAR(44) DEFAULT 'annotation' COMMENT 'annotation, info, link, damage, detail';
ALTER TABLE `object_3d_hotspot` MODIFY COLUMN `link_target` VARCHAR(22) DEFAULT '_blank' COMMENT '_self, _blank';
ALTER TABLE `object_3d_model` MODIFY COLUMN `ar_placement` VARCHAR(20) DEFAULT 'floor' COMMENT 'floor, wall';
ALTER TABLE `object_3d_model` MODIFY COLUMN `format` VARCHAR(39) DEFAULT 'glb' COMMENT 'glb, gltf, obj, fbx, stl, ply, usdz';
ALTER TABLE `object_3d_settings` MODIFY COLUMN `ar_placement` VARCHAR(20) DEFAULT 'floor' COMMENT 'floor, wall';
ALTER TABLE `object_3d_texture` MODIFY COLUMN `texture_type` VARCHAR(67) DEFAULT 'diffuse' COMMENT 'diffuse, normal, roughness, metallic, ao, emissive, environment';
ALTER TABLE `object_access_grant` MODIFY COLUMN `access_level` VARCHAR(28) DEFAULT 'view' COMMENT 'view, download, edit';
ALTER TABLE `object_access_grant` MODIFY COLUMN `object_type` VARCHAR(45) NOT NULL COMMENT 'information_object, repository, actor';
ALTER TABLE `physical_object_extended` MODIFY COLUMN `status` VARCHAR(48) DEFAULT 'active' COMMENT 'active, full, maintenance, decommissioned';
ALTER TABLE `preservation_backup_verification` MODIFY COLUMN `backup_type` VARCHAR(41) NOT NULL COMMENT 'database, files, full, incremental';
ALTER TABLE `preservation_backup_verification` MODIFY COLUMN `status` VARCHAR(47) NOT NULL COMMENT 'valid, invalid, missing, error, corrupted';
ALTER TABLE `preservation_checksum` MODIFY COLUMN `algorithm` VARCHAR(32) NOT NULL DEFAULT 'sha256' COMMENT 'md5, sha1, sha256, sha512';
ALTER TABLE `preservation_checksum` MODIFY COLUMN `verification_status` VARCHAR(37) DEFAULT 'pending' COMMENT 'pending, valid, invalid, error';
ALTER TABLE `preservation_event` MODIFY COLUMN `event_outcome` VARCHAR(41) DEFAULT 'unknown' COMMENT 'success, failure, warning, unknown';
ALTER TABLE `preservation_event` MODIFY COLUMN `event_type` VARCHAR(207) NOT NULL COMMENT 'creation, capture, ingestion, validation, fixity_check, virus_check, format_identification, normalization, migration, replication, deletion, deaccession, modification, metadata_modification, access, dissemination';
ALTER TABLE `preservation_event` MODIFY COLUMN `linking_agent_type` VARCHAR(43) DEFAULT 'system' COMMENT 'user, system, software, organization';
ALTER TABLE `preservation_fixity_check` MODIFY COLUMN `algorithm` VARCHAR(32) NOT NULL COMMENT 'md5, sha1, sha256, sha512';
ALTER TABLE `preservation_fixity_check` MODIFY COLUMN `status` VARCHAR(33) NOT NULL COMMENT 'pass, fail, error, missing';
ALTER TABLE `preservation_format` MODIFY COLUMN `preservation_action` VARCHAR(40) DEFAULT 'monitor' COMMENT 'none, monitor, migrate, normalize';
ALTER TABLE `preservation_format` MODIFY COLUMN `risk_level` VARCHAR(34) DEFAULT 'medium' COMMENT 'low, medium, high, critical';
ALTER TABLE `preservation_format_conversion` MODIFY COLUMN `status` VARCHAR(45) NOT NULL DEFAULT 'pending' COMMENT 'pending, processing, completed, failed';
ALTER TABLE `preservation_format_obsolescence` MODIFY COLUMN `current_risk_level` VARCHAR(34) NOT NULL COMMENT 'low, medium, high, critical';
ALTER TABLE `preservation_format_obsolescence` MODIFY COLUMN `migration_urgency` VARCHAR(39) DEFAULT 'none' COMMENT 'none, low, medium, high, critical';
ALTER TABLE `preservation_migration_pathway` MODIFY COLUMN `quality_impact` VARCHAR(47) DEFAULT 'minimal' COMMENT 'lossless, minimal, moderate, significant';
ALTER TABLE `preservation_migration_plan` MODIFY COLUMN `scope_type` VARCHAR(42) DEFAULT 'all' COMMENT 'all, repository, collection, custom';
ALTER TABLE `preservation_migration_plan` MODIFY COLUMN `status` VARCHAR(63) DEFAULT 'draft' COMMENT 'draft, approved, in_progress, completed, cancelled, failed';
ALTER TABLE `preservation_migration_plan_object` MODIFY COLUMN `status` VARCHAR(60) DEFAULT 'pending' COMMENT 'pending, queued, processing, completed, failed, skipped';
ALTER TABLE `preservation_object_format` MODIFY COLUMN `confidence` VARCHAR(33) DEFAULT 'medium' COMMENT 'low, medium, high, certain';
ALTER TABLE `preservation_package` MODIFY COLUMN `package_format` VARCHAR(33) NOT NULL DEFAULT 'bagit' COMMENT 'bagit, zip, tar, directory';
ALTER TABLE `preservation_package` MODIFY COLUMN `package_type` VARCHAR(21) NOT NULL COMMENT 'sip, aip, dip';
ALTER TABLE `preservation_package` MODIFY COLUMN `status` VARCHAR(58) NOT NULL DEFAULT 'draft' COMMENT 'draft, building, complete, validated, exported, error';
ALTER TABLE `preservation_package_event` MODIFY COLUMN `event_outcome` VARCHAR(33) DEFAULT 'success' COMMENT 'success, failure, warning';
ALTER TABLE `preservation_package_event` MODIFY COLUMN `event_type` VARCHAR(89) NOT NULL COMMENT 'creation, modification, building, validation, export, import, transfer, deletion, error';
ALTER TABLE `preservation_package_object` MODIFY COLUMN `object_role` VARCHAR(43) DEFAULT 'payload' COMMENT 'payload, metadata, manifest, tagfile';
ALTER TABLE `preservation_policy` MODIFY COLUMN `policy_type` VARCHAR(45) NOT NULL COMMENT 'fixity, format, retention, replication';
ALTER TABLE `preservation_replication_log` MODIFY COLUMN `operation` VARCHAR(29) NOT NULL COMMENT 'sync, verify, restore';
ALTER TABLE `preservation_replication_log` MODIFY COLUMN `status` VARCHAR(42) NOT NULL COMMENT 'started, completed, failed, partial';
ALTER TABLE `preservation_replication_target` MODIFY COLUMN `last_sync_status` VARCHAR(32) DEFAULT NULL COMMENT 'success, partial, failed';
ALTER TABLE `preservation_replication_target` MODIFY COLUMN `target_type` VARCHAR(39) NOT NULL COMMENT 'local, sftp, s3, azure, gcs, rsync';
ALTER TABLE `preservation_virus_scan` MODIFY COLUMN `status` VARCHAR(38) NOT NULL COMMENT 'clean, infected, error, skipped';
ALTER TABLE `preservation_workflow_run` MODIFY COLUMN `status` VARCHAR(52) NOT NULL DEFAULT 'running' COMMENT 'running, completed, failed, timeout, cancelled';
ALTER TABLE `preservation_workflow_run` MODIFY COLUMN `triggered_by` VARCHAR(30) DEFAULT 'scheduler' COMMENT 'scheduler, manual, api';
ALTER TABLE `preservation_workflow_schedule` MODIFY COLUMN `last_run_status` VARCHAR(40) DEFAULT NULL COMMENT 'success, partial, failed, timeout';
ALTER TABLE `preservation_workflow_schedule` MODIFY COLUMN `schedule_type` VARCHAR(30) NOT NULL DEFAULT 'cron' COMMENT 'cron, interval, manual';
ALTER TABLE `preservation_workflow_schedule` MODIFY COLUMN `workflow_type` VARCHAR(105) NOT NULL COMMENT 'format_identification, fixity_check, virus_scan, format_conversion, backup_verification, replication';
ALTER TABLE `privacy_breach` MODIFY COLUMN `breach_type` VARCHAR(48) NOT NULL COMMENT 'confidentiality, integrity, availability';
ALTER TABLE `privacy_breach` MODIFY COLUMN `risk_to_rights` VARCHAR(39) DEFAULT NULL COMMENT 'unlikely, possible, likely, high';
ALTER TABLE `privacy_breach` MODIFY COLUMN `severity` VARCHAR(34) NOT NULL DEFAULT 'medium' COMMENT 'low, medium, high, critical';
ALTER TABLE `privacy_breach` MODIFY COLUMN `status` VARCHAR(58) NOT NULL DEFAULT 'detected' COMMENT 'detected, investigating, contained, resolved, closed';
ALTER TABLE `privacy_breach_notification` MODIFY COLUMN `method` VARCHAR(45) NOT NULL COMMENT 'email, letter, portal, phone, in_person';
ALTER TABLE `privacy_breach_notification` MODIFY COLUMN `notification_type` VARCHAR(53) NOT NULL COMMENT 'regulator, data_subject, internal, third_party';
ALTER TABLE `privacy_complaint` MODIFY COLUMN `status` VARCHAR(58) DEFAULT 'received' COMMENT 'received, investigating, resolved, escalated, closed';
ALTER TABLE `privacy_compliance_rule` MODIFY COLUMN `severity` VARCHAR(28) DEFAULT 'error' COMMENT 'error, warning, info';
ALTER TABLE `privacy_consent` MODIFY COLUMN `consent_type` VARCHAR(86) NOT NULL COMMENT 'processing, marketing, profiling, third_party, cookies, research, special_category';
ALTER TABLE `privacy_consent_log` MODIFY COLUMN `action` VARCHAR(43) NOT NULL COMMENT 'granted, withdrawn, expired, renewed';
ALTER TABLE `privacy_data_inventory` MODIFY COLUMN `data_type` VARCHAR(88) NOT NULL COMMENT 'personal, special_category, children, criminal, financial, health, biometric, genetic';
ALTER TABLE `privacy_data_inventory` MODIFY COLUMN `storage_format` VARCHAR(31) NOT NULL DEFAULT 'electronic' COMMENT 'electronic, paper, both';
ALTER TABLE `privacy_dsar` MODIFY COLUMN `outcome` VARCHAR(58) DEFAULT NULL COMMENT 'granted, partially_granted, refused, not_applicable';
ALTER TABLE `privacy_dsar` MODIFY COLUMN `priority` VARCHAR(32) NOT NULL DEFAULT 'normal' COMMENT 'low, normal, high, urgent';
ALTER TABLE `privacy_dsar` MODIFY COLUMN `request_type` VARCHAR(89) NOT NULL COMMENT 'access, rectification, erasure, portability, restriction, objection, withdraw_consent';
ALTER TABLE `privacy_dsar` MODIFY COLUMN `status` VARCHAR(81) NOT NULL DEFAULT 'received' COMMENT 'received, verified, in_progress, pending_info, completed, rejected, withdrawn';
ALTER TABLE `privacy_paia_request` MODIFY COLUMN `access_form` VARCHAR(27) NOT NULL DEFAULT 'copy' COMMENT 'inspect, copy, both';
ALTER TABLE `privacy_paia_request` MODIFY COLUMN `paia_section` VARCHAR(64) NOT NULL COMMENT 'section_18, section_22, section_23, section_50, section_77';
ALTER TABLE `privacy_paia_request` MODIFY COLUMN `status` VARCHAR(84) NOT NULL DEFAULT 'received' COMMENT 'received, processing, granted, partially_granted, refused, transferred, appealed';
ALTER TABLE `privacy_redaction_cache` MODIFY COLUMN `file_type` VARCHAR(20) NOT NULL DEFAULT 'pdf' COMMENT 'pdf, image';
ALTER TABLE `privacy_retention_schedule` MODIFY COLUMN `disposal_action` VARCHAR(42) NOT NULL DEFAULT 'destroy' COMMENT 'destroy, archive, anonymize, review';
ALTER TABLE `privacy_visual_redaction` MODIFY COLUMN `region_type` VARCHAR(36) NOT NULL DEFAULT 'rectangle' COMMENT 'rectangle, polygon, freehand';
ALTER TABLE `privacy_visual_redaction` MODIFY COLUMN `source` VARCHAR(43) NOT NULL DEFAULT 'manual' COMMENT 'manual, auto_ner, auto_pii, imported';
ALTER TABLE `privacy_visual_redaction` MODIFY COLUMN `status` VARCHAR(43) NOT NULL DEFAULT 'pending' COMMENT 'pending, approved, applied, rejected';
ALTER TABLE `provenance_agent` MODIFY COLUMN `agent_type` VARCHAR(44) DEFAULT 'person' COMMENT 'person, organization, family, unknown';
ALTER TABLE `provenance_document` MODIFY COLUMN `document_type` VARCHAR(299) NOT NULL DEFAULT 'other' COMMENT 'deed_of_gift, bill_of_sale, invoice, receipt, auction_catalog, exhibition_catalog, inventory, insurance_record, photograph, correspondence, certificate, customs_document, export_license, import_permit, appraisal, condition_report, newspaper_clipping, publication, oral_history, affidavit, legal_document, other';
ALTER TABLE `provenance_entry` MODIFY COLUMN `certainty` VARCHAR(53) NOT NULL DEFAULT 'unknown' COMMENT 'certain, probable, possible, uncertain, unknown';
ALTER TABLE `provenance_entry` MODIFY COLUMN `end_date_qualifier` VARCHAR(31) DEFAULT NULL COMMENT 'circa, before, after, by';
ALTER TABLE `provenance_entry` MODIFY COLUMN `owner_type` VARCHAR(97) NOT NULL DEFAULT 'unknown' COMMENT 'person, family, dealer, auction_house, museum, corporate, government, religious, artist, unknown';
ALTER TABLE `provenance_entry` MODIFY COLUMN `start_date_qualifier` VARCHAR(31) DEFAULT NULL COMMENT 'circa, before, after, by';
ALTER TABLE `provenance_entry` MODIFY COLUMN `transfer_type` VARCHAR(123) NOT NULL DEFAULT 'unknown' COMMENT 'sale, auction, gift, bequest, inheritance, commission, exchange, seizure, restitution, transfer, loan, found, created, unknown';
ALTER TABLE `provenance_event` MODIFY COLUMN `certainty` VARCHAR(45) DEFAULT 'uncertain' COMMENT 'certain, probable, possible, uncertain';
ALTER TABLE `provenance_event` MODIFY COLUMN `date_certainty` VARCHAR(45) DEFAULT 'unknown' COMMENT 'exact, approximate, estimated, unknown';
ALTER TABLE `provenance_event` MODIFY COLUMN `event_type` VARCHAR(331) NOT NULL DEFAULT 'unknown' COMMENT 'creation, commission, sale, purchase, auction, gift, donation, bequest, inheritance, descent, loan_out, loan_return, deposit, withdrawal, transfer, exchange, theft, recovery, confiscation, restitution, repatriation, discovery, excavation, import, export, authentication, appraisal, conservation, restoration, accessioning, deaccessioning, unknown, other';
ALTER TABLE `provenance_event` MODIFY COLUMN `evidence_type` VARCHAR(55) DEFAULT 'none' COMMENT 'documentary, physical, oral, circumstantial, none';
ALTER TABLE `provenance_record` MODIFY COLUMN `acquisition_type` VARCHAR(91) DEFAULT 'unknown' COMMENT 'donation, purchase, bequest, transfer, loan, deposit, exchange, field_collection, unknown';
ALTER TABLE `provenance_record` MODIFY COLUMN `certainty_level` VARCHAR(53) DEFAULT 'unknown' COMMENT 'certain, probable, possible, uncertain, unknown';
ALTER TABLE `provenance_record` MODIFY COLUMN `cultural_property_status` VARCHAR(51) DEFAULT 'none' COMMENT 'none, claimed, disputed, repatriated, cleared';
ALTER TABLE `provenance_record` MODIFY COLUMN `current_status` VARCHAR(50) DEFAULT 'owned' COMMENT 'owned, on_loan, deposited, unknown, disputed';
ALTER TABLE `provenance_record` MODIFY COLUMN `custody_type` VARCHAR(42) DEFAULT 'permanent' COMMENT 'permanent, temporary, loan, deposit';
ALTER TABLE `provenance_record` MODIFY COLUMN `research_status` VARCHAR(55) DEFAULT 'not_started' COMMENT 'not_started, in_progress, complete, inconclusive';
ALTER TABLE `registry_attachment` MODIFY COLUMN `entity_type` VARCHAR(64) NOT NULL COMMENT 'discussion, reply, blog_post, institution, vendor, software';
ALTER TABLE `registry_attachment` MODIFY COLUMN `file_type` VARCHAR(53) DEFAULT 'other' COMMENT 'image, document, log, archive, screenshot, other';
ALTER TABLE `registry_blog_post` MODIFY COLUMN `author_type` VARCHAR(45) NOT NULL COMMENT 'admin, vendor, institution, user_group';
ALTER TABLE `registry_blog_post` MODIFY COLUMN `category` VARCHAR(77) DEFAULT 'news' COMMENT 'news, announcement, event, tutorial, case_study, release, community, other';
ALTER TABLE `registry_blog_post` MODIFY COLUMN `status` VARCHAR(49) DEFAULT 'draft' COMMENT 'draft, pending_review, published, archived';
ALTER TABLE `registry_contact` MODIFY COLUMN `entity_type` VARCHAR(28) NOT NULL COMMENT 'institution, vendor';
ALTER TABLE `registry_discussion` MODIFY COLUMN `status` VARCHAR(35) DEFAULT 'active' COMMENT 'active, closed, hidden, spam';
ALTER TABLE `registry_discussion` MODIFY COLUMN `topic_type` VARCHAR(62) DEFAULT 'discussion' COMMENT 'discussion, question, announcement, event, showcase, help';
ALTER TABLE `registry_discussion_reply` MODIFY COLUMN `status` VARCHAR(28) DEFAULT 'active' COMMENT 'active, hidden, spam';
ALTER TABLE `registry_favorite` MODIFY COLUMN `entity_type` VARCHAR(43) NOT NULL COMMENT 'institution, vendor, software, group';
ALTER TABLE `registry_instance` MODIFY COLUMN `hosting` VARCHAR(46) DEFAULT NULL COMMENT 'self_hosted, cloud, vendor_hosted, saas';
ALTER TABLE `registry_instance` MODIFY COLUMN `instance_type` VARCHAR(53) DEFAULT 'production' COMMENT 'production, staging, development, demo, offline';
ALTER TABLE `registry_instance` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'online' COMMENT 'online, offline, maintenance, decommissioned';
ALTER TABLE `registry_institution` MODIFY COLUMN `governance` VARCHAR(65) DEFAULT NULL COMMENT 'public, private, ngo, academic, government, tribal, community';
ALTER TABLE `registry_institution` MODIFY COLUMN `institution_type` VARCHAR(102) NOT NULL COMMENT 'archive, library, museum, gallery, dam, heritage_site, research_centre, government, university, other';
ALTER TABLE `registry_institution` MODIFY COLUMN `size` VARCHAR(37) DEFAULT NULL COMMENT 'small, medium, large, national';
ALTER TABLE `registry_newsletter` MODIFY COLUMN `status` VARCHAR(40) DEFAULT 'draft' COMMENT 'draft, scheduled, sent, cancelled';
ALTER TABLE `registry_newsletter_send_log` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'queued' COMMENT 'queued, sent, failed, bounced, opened, clicked';
ALTER TABLE `registry_newsletter_subscriber` MODIFY COLUMN `status` VARCHAR(37) DEFAULT 'active' COMMENT 'active, unsubscribed, bounced';
ALTER TABLE `registry_oauth_account` MODIFY COLUMN `provider` VARCHAR(51) NOT NULL COMMENT 'google, facebook, github, linkedin, microsoft';
ALTER TABLE `registry_review` MODIFY COLUMN `entity_type` VARCHAR(25) NOT NULL COMMENT 'vendor, software';
ALTER TABLE `registry_settings` MODIFY COLUMN `setting_type` VARCHAR(34) DEFAULT 'text' COMMENT 'text, number, boolean, json';
ALTER TABLE `registry_software` MODIFY COLUMN `category` VARCHAR(110) NOT NULL COMMENT 'ams, ims, dam, dams, cms, preservation, digitization, discovery, utility, plugin, integration, theme, glam, other';
ALTER TABLE `registry_software` MODIFY COLUMN `git_provider` VARCHAR(50) DEFAULT 'none' COMMENT 'github, gitlab, bitbucket, self_hosted, none';
ALTER TABLE `registry_software` MODIFY COLUMN `pricing_model` VARCHAR(65) DEFAULT 'open_source' COMMENT 'free, open_source, freemium, subscription, one_time, contact';
ALTER TABLE `registry_software_component` MODIFY COLUMN `component_type` VARCHAR(65) DEFAULT 'plugin' COMMENT 'plugin, module, extension, theme, integration, library, other';
ALTER TABLE `registry_software_release` MODIFY COLUMN `release_type` VARCHAR(41) DEFAULT 'patch' COMMENT 'major, minor, patch, beta, rc, alpha';
ALTER TABLE `registry_sync_log` MODIFY COLUMN `event_type` VARCHAR(46) NOT NULL COMMENT 'register, heartbeat, sync, update, error';
ALTER TABLE `registry_sync_log` MODIFY COLUMN `status` VARCHAR(23) DEFAULT 'success' COMMENT 'success, error';
ALTER TABLE `registry_tag` MODIFY COLUMN `entity_type` VARCHAR(37) NOT NULL COMMENT 'institution, vendor, software';
ALTER TABLE `registry_user_group` MODIFY COLUMN `group_type` VARCHAR(53) DEFAULT 'regional' COMMENT 'regional, topic, software, institutional, other';
ALTER TABLE `registry_user_group` MODIFY COLUMN `meeting_format` VARCHAR(34) DEFAULT NULL COMMENT 'in_person, virtual, hybrid';
ALTER TABLE `registry_user_group` MODIFY COLUMN `meeting_frequency` VARCHAR(56) DEFAULT NULL COMMENT 'weekly, biweekly, monthly, quarterly, annual, adhoc';
ALTER TABLE `registry_user_group_member` MODIFY COLUMN `role` VARCHAR(55) DEFAULT 'member' COMMENT 'organizer, co_organizer, member, speaker, sponsor';
ALTER TABLE `registry_vendor` MODIFY COLUMN `team_size` VARCHAR(33) DEFAULT NULL COMMENT 'solo, 2-5, 6-20, 21-50, 50+';
ALTER TABLE `registry_vendor_call_log` MODIFY COLUMN `direction` VARCHAR(26) DEFAULT 'outbound' COMMENT 'inbound, outbound';
ALTER TABLE `registry_vendor_call_log` MODIFY COLUMN `interaction_type` VARCHAR(71) NOT NULL DEFAULT 'call' COMMENT 'call, email, meeting, support_ticket, site_visit, video_call, other';
ALTER TABLE `registry_vendor_call_log` MODIFY COLUMN `priority` VARCHAR(32) DEFAULT 'medium' COMMENT 'low, medium, high, urgent';
ALTER TABLE `registry_vendor_call_log` MODIFY COLUMN `status` VARCHAR(52) DEFAULT 'open' COMMENT 'open, in_progress, resolved, closed, escalated';
ALTER TABLE `registry_vendor_institution` MODIFY COLUMN `relationship_type` VARCHAR(84) NOT NULL COMMENT 'developer, hosting, maintenance, consulting, digitization, training, integration';
ALTER TABLE `report_definition` MODIFY COLUMN `category` VARCHAR(92) NOT NULL COMMENT 'collection, acquisition, access, preservation, researcher, compliance, statistics, custom';
ALTER TABLE `report_link` MODIFY COLUMN `link_type` VARCHAR(79) NOT NULL COMMENT 'external, information_object, actor, repository, accession, digital_object';
ALTER TABLE `report_query` MODIFY COLUMN `query_type` VARCHAR(24) DEFAULT 'visual' COMMENT 'visual, raw_sql';
ALTER TABLE `report_schedule` MODIFY COLUMN `frequency` VARCHAR(40) NOT NULL COMMENT 'daily, weekly, monthly, quarterly';
ALTER TABLE `report_schedule` MODIFY COLUMN `output_format` VARCHAR(22) DEFAULT 'pdf' COMMENT 'pdf, xlsx, csv';
ALTER TABLE `report_schedule` MODIFY COLUMN `schedule_type` VARCHAR(27) DEFAULT 'recurring' COMMENT 'recurring, trigger';
ALTER TABLE `report_section` MODIFY COLUMN `section_type` VARCHAR(74) NOT NULL COMMENT 'narrative, table, chart, summary_card, image_gallery, links, sql_query';
ALTER TABLE `report_template` MODIFY COLUMN `scope` VARCHAR(33) DEFAULT 'user' COMMENT 'system, institution, user';
ALTER TABLE `reproduction_request` MODIFY COLUMN `status` VARCHAR(55) DEFAULT 'pending' COMMENT 'pending, approved, rejected, completed, cancelled';
ALTER TABLE `research_access_decision` MODIFY COLUMN `decision` VARCHAR(26) NOT NULL COMMENT 'permitted, denied';
ALTER TABLE `research_activity` MODIFY COLUMN `activity_type` VARCHAR(86) NOT NULL COMMENT 'class, tour, exhibit, loan, conservation, photography, filming, event, meeting, other';
ALTER TABLE `research_activity` MODIFY COLUMN `status` VARCHAR(71) DEFAULT 'requested' COMMENT 'requested, tentative, confirmed, in_progress, completed, cancelled';
ALTER TABLE `research_activity_log` MODIFY COLUMN `activity_type` VARCHAR(348) NOT NULL COMMENT 'view, search, download, cite, annotate, collect, book, request, export, share, login, logout, snapshot_created, snapshot_compared, assertion_created, assertion_verified, assertion_disputed, extraction_queued, extraction_completed, validation_accepted, validation_rejected, hypothesis_created, hypothesis_updated, policy_evaluated, doi_minted, create, clipboard_add';
ALTER TABLE `research_activity_material` MODIFY COLUMN `status` VARCHAR(71) DEFAULT 'requested' COMMENT 'requested, approved, rejected, retrieved, in_use, returned, damaged';
ALTER TABLE `research_activity_participant` MODIFY COLUMN `registration_status` VARCHAR(63) DEFAULT 'pending' COMMENT 'pending, confirmed, waitlist, cancelled, attended, no_show';
ALTER TABLE `research_activity_participant` MODIFY COLUMN `role` VARCHAR(78) DEFAULT 'visitor' COMMENT 'organizer, instructor, presenter, student, visitor, assistant, staff, other';
ALTER TABLE `research_annotation` MODIFY COLUMN `annotation_type` VARCHAR(51) DEFAULT 'note' COMMENT 'note, highlight, bookmark, tag, transcription';
ALTER TABLE `research_annotation` MODIFY COLUMN `content_format` VARCHAR(20) DEFAULT 'text' COMMENT 'text, html';
ALTER TABLE `research_annotation` MODIFY COLUMN `visibility` VARCHAR(31) DEFAULT 'private' COMMENT 'private, shared, public';
ALTER TABLE `research_annotation_target` MODIFY COLUMN `selector_type` VARCHAR(97) DEFAULT NULL COMMENT 'TextQuoteSelector, FragmentSelector, SvgSelector, PointSelector, RangeSelector, TimeSelector';
ALTER TABLE `research_annotation_v2` MODIFY COLUMN `motivation` VARCHAR(84) NOT NULL DEFAULT 'commenting' COMMENT 'commenting, describing, classifying, linking, questioning, tagging, highlighting';
ALTER TABLE `research_annotation_v2` MODIFY COLUMN `status` VARCHAR(33) DEFAULT 'active' COMMENT 'active, archived, deleted';
ALTER TABLE `research_annotation_v2` MODIFY COLUMN `visibility` VARCHAR(31) DEFAULT 'private' COMMENT 'private, shared, public';
ALTER TABLE `research_assertion` MODIFY COLUMN `assertion_type` VARCHAR(67) NOT NULL COMMENT 'biographical, chronological, spatial, relational, attributive';
ALTER TABLE `research_assertion` MODIFY COLUMN `status` VARCHAR(46) DEFAULT 'proposed' COMMENT 'proposed, verified, disputed, retracted';
ALTER TABLE `research_assertion_evidence` MODIFY COLUMN `relationship` VARCHAR(26) NOT NULL COMMENT 'supports, refutes';
ALTER TABLE `research_bibliography_entry` MODIFY COLUMN `entry_type` VARCHAR(60) DEFAULT 'archival' COMMENT 'archival, book, article, chapter, thesis, website, other';
ALTER TABLE `research_booking` MODIFY COLUMN `status` VARCHAR(55) DEFAULT 'pending' COMMENT 'pending, confirmed, cancelled, completed, no_show';
ALTER TABLE `research_comment` MODIFY COLUMN `entity_type` VARCHAR(67) NOT NULL COMMENT 'report, report_section, annotation, journal_entry, collection';
ALTER TABLE `research_entity_resolution` MODIFY COLUMN `status` VARCHAR(36) DEFAULT 'proposed' COMMENT 'proposed, accepted, rejected';
ALTER TABLE `research_equipment` MODIFY COLUMN `condition_status` VARCHAR(57) DEFAULT 'good' COMMENT 'excellent, good, fair, needs_repair, out_of_service';
ALTER TABLE `research_equipment` MODIFY COLUMN `equipment_type` VARCHAR(127) NOT NULL COMMENT 'microfilm_reader, microfiche_reader, scanner, computer, magnifier, book_cradle, light_box, camera_stand, gloves, weights, other';
ALTER TABLE `research_equipment_booking` MODIFY COLUMN `condition_on_return` VARCHAR(37) DEFAULT NULL COMMENT 'excellent, good, fair, damaged';
ALTER TABLE `research_equipment_booking` MODIFY COLUMN `status` VARCHAR(52) DEFAULT 'reserved' COMMENT 'reserved, in_use, returned, cancelled, no_show';
ALTER TABLE `research_external_collaborator` MODIFY COLUMN `role` VARCHAR(28) DEFAULT 'viewer' COMMENT 'viewer, contributor';
ALTER TABLE `research_extraction_job` MODIFY COLUMN `extraction_type` VARCHAR(79) NOT NULL COMMENT 'ocr, ner, summarize, translate, spellcheck, face_detection, form_extraction';
ALTER TABLE `research_extraction_job` MODIFY COLUMN `status` VARCHAR(41) DEFAULT 'queued' COMMENT 'queued, running, completed, failed';
ALTER TABLE `research_extraction_result` MODIFY COLUMN `result_type` VARCHAR(66) NOT NULL COMMENT 'entity, summary, translation, transcription, form_field, face';
ALTER TABLE `research_hypothesis` MODIFY COLUMN `status` VARCHAR(44) DEFAULT 'proposed' COMMENT 'proposed, testing, supported, refuted';
ALTER TABLE `research_hypothesis_evidence` MODIFY COLUMN `relationship` VARCHAR(34) NOT NULL COMMENT 'supports, refutes, neutral';
ALTER TABLE `research_institutional_share` MODIFY COLUMN `share_type` VARCHAR(30) DEFAULT 'view' COMMENT 'view, contribute, full';
ALTER TABLE `research_institutional_share` MODIFY COLUMN `status` VARCHAR(40) DEFAULT 'pending' COMMENT 'pending, active, revoked, expired';
ALTER TABLE `research_journal_entry` MODIFY COLUMN `content_format` VARCHAR(20) DEFAULT 'html' COMMENT 'text, html';
ALTER TABLE `research_journal_entry` MODIFY COLUMN `entry_type` VARCHAR(108) DEFAULT 'manual' COMMENT 'manual, auto_booking, auto_material, auto_annotation, auto_search, auto_collection, reflection, milestone';
ALTER TABLE `research_material_request` MODIFY COLUMN `priority` VARCHAR(26) DEFAULT 'normal' COMMENT 'normal, high, rush';
ALTER TABLE `research_material_request` MODIFY COLUMN `request_type` VARCHAR(54) DEFAULT 'reading_room' COMMENT 'reading_room, reproduction, loan, remote_access';
ALTER TABLE `research_material_request` MODIFY COLUMN `status` VARCHAR(67) DEFAULT 'requested' COMMENT 'requested, retrieved, delivered, in_use, returned, unavailable';
ALTER TABLE `research_notification` MODIFY COLUMN `type` VARCHAR(70) NOT NULL COMMENT 'alert, invitation, comment, reply, system, reminder, collaboration';
ALTER TABLE `research_notification_preference` MODIFY COLUMN `digest_frequency` VARCHAR(37) DEFAULT 'immediate' COMMENT 'immediate, daily, weekly, none';
ALTER TABLE `research_peer_review` MODIFY COLUMN `status` VARCHAR(48) DEFAULT 'pending' COMMENT 'pending, in_progress, completed, declined';
ALTER TABLE `research_print_template` MODIFY COLUMN `orientation` VARCHAR(28) DEFAULT 'portrait' COMMENT 'portrait, landscape';
ALTER TABLE `research_print_template` MODIFY COLUMN `page_size` VARCHAR(55) DEFAULT 'a4' COMMENT 'a4, a5, letter, label_4x6, label_2x4, badge, custom';
ALTER TABLE `research_print_template` MODIFY COLUMN `template_type` VARCHAR(65) NOT NULL COMMENT 'call_slip, paging_slip, receipt, badge, label, report, letter';
ALTER TABLE `research_project` MODIFY COLUMN `project_type` VARCHAR(103) DEFAULT 'personal' COMMENT 'thesis, dissertation, publication, exhibition, documentary, genealogy, institutional, personal, other';
ALTER TABLE `research_project` MODIFY COLUMN `status` VARCHAR(52) DEFAULT 'planning' COMMENT 'planning, active, on_hold, completed, archived';
ALTER TABLE `research_project` MODIFY COLUMN `visibility` VARCHAR(38) DEFAULT 'private' COMMENT 'private, collaborators, public';
ALTER TABLE `research_project_collaborator` MODIFY COLUMN `role` VARCHAR(41) DEFAULT 'contributor' COMMENT 'owner, editor, contributor, viewer';
ALTER TABLE `research_project_collaborator` MODIFY COLUMN `status` VARCHAR(43) DEFAULT 'pending' COMMENT 'pending, accepted, declined, removed';
ALTER TABLE `research_project_milestone` MODIFY COLUMN `status` VARCHAR(49) DEFAULT 'pending' COMMENT 'pending, in_progress, completed, cancelled';
ALTER TABLE `research_project_resource` MODIFY COLUMN `link_type` VARCHAR(73) DEFAULT NULL COMMENT 'academic, archive, database, government, website, social_media, other';
ALTER TABLE `research_project_resource` MODIFY COLUMN `resource_type` VARCHAR(92) NOT NULL COMMENT 'collection, saved_search, annotation, bibliography, object, external_link, document, note';
ALTER TABLE `research_quality_metric` MODIFY COLUMN `metric_type` VARCHAR(78) NOT NULL COMMENT 'ocr_confidence, image_quality, digitisation_completeness, fixity_status';
ALTER TABLE `research_reading_room_seat` MODIFY COLUMN `seat_type` VARCHAR(69) DEFAULT 'standard' COMMENT 'standard, accessible, computer, microfilm, oversize, quiet, group';
ALTER TABLE `research_report` MODIFY COLUMN `status` VARCHAR(53) DEFAULT 'draft' COMMENT 'draft, in_progress, review, completed, archived';
ALTER TABLE `research_report` MODIFY COLUMN `template_type` VARCHAR(85) DEFAULT 'custom' COMMENT 'research_summary, genealogical, historical, source_analysis, finding_aid, custom';
ALTER TABLE `research_report_section` MODIFY COLUMN `content_format` VARCHAR(20) DEFAULT 'html' COMMENT 'text, html';
ALTER TABLE `research_report_section` MODIFY COLUMN `section_type` VARCHAR(98) DEFAULT 'text' COMMENT 'title_page, toc, heading, text, bibliography, collection_list, annotation_list, timeline, custom';
ALTER TABLE `research_reproduction_item` MODIFY COLUMN `color_mode` VARCHAR(28) DEFAULT 'grayscale' COMMENT 'color, grayscale, bw';
ALTER TABLE `research_reproduction_item` MODIFY COLUMN `reproduction_type` VARCHAR(120) DEFAULT 'scan' COMMENT 'photocopy, scan, photograph, digital_copy, digital_scan, transcription, certification, certified_copy, microfilm, other';
ALTER TABLE `research_reproduction_item` MODIFY COLUMN `status` VARCHAR(49) DEFAULT 'pending' COMMENT 'pending, in_progress, completed, cancelled';
ALTER TABLE `research_reproduction_request` MODIFY COLUMN `delivery_method` VARCHAR(69) DEFAULT 'email' COMMENT 'email, download, post, collect, digital, pickup, courier, physical';
ALTER TABLE `research_reproduction_request` MODIFY COLUMN `status` VARCHAR(87) DEFAULT 'draft' COMMENT 'draft, submitted, processing, awaiting_payment, in_production, completed, cancelled';
ALTER TABLE `research_request_queue` MODIFY COLUMN `queue_type` VARCHAR(57) DEFAULT 'retrieval' COMMENT 'retrieval, paging, return, curatorial, reproduction';
ALTER TABLE `research_request_queue` MODIFY COLUMN `sort_direction` VARCHAR(20) DEFAULT 'ASC' COMMENT 'ASC, DESC';
ALTER TABLE `research_request_status_history` MODIFY COLUMN `request_type` VARCHAR(31) NOT NULL DEFAULT 'material' COMMENT 'material, reproduction';
ALTER TABLE `research_researcher` MODIFY COLUMN `affiliation_type` VARCHAR(63) DEFAULT 'independent' COMMENT 'academic, government, private, independent, student, other';
ALTER TABLE `research_researcher` MODIFY COLUMN `id_type` VARCHAR(65) DEFAULT NULL COMMENT 'passport, national_id, drivers_license, student_card, other';
ALTER TABLE `research_researcher` MODIFY COLUMN `status` VARCHAR(53) DEFAULT 'pending' COMMENT 'pending, approved, suspended, expired, rejected';
ALTER TABLE `research_rights_policy` MODIFY COLUMN `action_type` VARCHAR(57) NOT NULL COMMENT 'use, reproduce, distribute, modify, archive, display';
ALTER TABLE `research_rights_policy` MODIFY COLUMN `policy_type` VARCHAR(43) NOT NULL COMMENT 'permission, prohibition, obligation';
ALTER TABLE `research_room` MODIFY COLUMN `status` VARCHAR(31) DEFAULT 'draft' COMMENT 'draft, active, archived';
ALTER TABLE `research_room_manifest` MODIFY COLUMN `derivative_type` VARCHAR(31) DEFAULT 'full' COMMENT 'full, subset, annotated';
ALTER TABLE `research_room_participant` MODIFY COLUMN `role` VARCHAR(29) DEFAULT 'viewer' COMMENT 'owner, editor, viewer';
ALTER TABLE `research_saved_search` MODIFY COLUMN `alert_frequency` VARCHAR(30) DEFAULT 'weekly' COMMENT 'daily, weekly, monthly';
ALTER TABLE `research_seat_assignment` MODIFY COLUMN `status` VARCHAR(44) DEFAULT 'assigned' COMMENT 'assigned, occupied, released, no_show';
ALTER TABLE `research_snapshot` MODIFY COLUMN `status` VARCHAR(32) DEFAULT 'active' COMMENT 'active, frozen, archived';
ALTER TABLE `research_source_assessment` MODIFY COLUMN `completeness` VARCHAR(58) DEFAULT 'complete' COMMENT 'complete, partial, fragment, missing_pages, redacted';
ALTER TABLE `research_source_assessment` MODIFY COLUMN `source_form` VARCHAR(62) DEFAULT 'original' COMMENT 'born_digital, scan, original, transcription, translation';
ALTER TABLE `research_source_assessment` MODIFY COLUMN `source_type` VARCHAR(36) NOT NULL COMMENT 'primary, secondary, tertiary';
ALTER TABLE `research_timeline_event` MODIFY COLUMN `date_type` VARCHAR(46) DEFAULT 'event' COMMENT 'event, creation, accession, publication';
ALTER TABLE `research_validation_queue` MODIFY COLUMN `status` VARCHAR(44) DEFAULT 'pending' COMMENT 'pending, accepted, rejected, modified';
ALTER TABLE `research_verification` MODIFY COLUMN `status` VARCHAR(43) DEFAULT 'pending' COMMENT 'pending, verified, rejected, expired';
ALTER TABLE `research_verification` MODIFY COLUMN `verification_type` VARCHAR(113) NOT NULL COMMENT 'id_document, institutional_letter, institutional_email, orcid, staff_approval, professional_membership, other';
ALTER TABLE `research_walk_in_visitor` MODIFY COLUMN `id_type` VARCHAR(65) DEFAULT NULL COMMENT 'passport, national_id, drivers_license, student_card, other';
ALTER TABLE `research_workspace` MODIFY COLUMN `visibility` VARCHAR(32) DEFAULT 'private' COMMENT 'private, members, public';
ALTER TABLE `research_workspace_member` MODIFY COLUMN `role` VARCHAR(54) DEFAULT 'viewer' COMMENT 'owner, admin, editor, viewer, member, contributor';
ALTER TABLE `research_workspace_member` MODIFY COLUMN `status` VARCHAR(43) DEFAULT 'pending' COMMENT 'pending, accepted, declined, removed';
ALTER TABLE `research_workspace_resource` MODIFY COLUMN `resource_type` VARCHAR(68) NOT NULL COMMENT 'collection, project, bibliography, saved_search, document, link';
ALTER TABLE `researcher_submission` MODIFY COLUMN `source_type` VARCHAR(24) NOT NULL DEFAULT 'online' COMMENT 'online, offline';
ALTER TABLE `researcher_submission` MODIFY COLUMN `status` VARCHAR(75) NOT NULL DEFAULT 'draft' COMMENT 'draft, submitted, under_review, approved, published, returned, rejected';
ALTER TABLE `researcher_submission_item` MODIFY COLUMN `item_type` VARCHAR(45) NOT NULL DEFAULT 'description' COMMENT 'description, note, repository, creator';
ALTER TABLE `researcher_submission_review` MODIFY COLUMN `action` VARCHAR(47) NOT NULL COMMENT 'comment, return, approve, reject, publish';
ALTER TABLE `ric_orphan_tracking` MODIFY COLUMN `detection_method` VARCHAR(45) NOT NULL COMMENT 'integrity_check, sync_failure, manual';
ALTER TABLE `ric_orphan_tracking` MODIFY COLUMN `status` VARCHAR(53) NOT NULL DEFAULT 'detected' COMMENT 'detected, reviewed, cleaned, retained, restored';
ALTER TABLE `ric_sync_log` MODIFY COLUMN `operation` VARCHAR(66) NOT NULL COMMENT 'create, update, delete, move, resync, cleanup, integrity_check';
ALTER TABLE `ric_sync_log` MODIFY COLUMN `status` VARCHAR(41) NOT NULL COMMENT 'success, failure, partial, skipped';
ALTER TABLE `ric_sync_log` MODIFY COLUMN `triggered_by` VARCHAR(34) NOT NULL DEFAULT 'system' COMMENT 'user, system, cron, api, cli';
ALTER TABLE `ric_sync_queue` MODIFY COLUMN `operation` VARCHAR(35) NOT NULL COMMENT 'create, update, delete, move';
ALTER TABLE `ric_sync_queue` MODIFY COLUMN `status` VARCHAR(54) NOT NULL DEFAULT 'queued' COMMENT 'queued, processing, completed, failed, cancelled';
ALTER TABLE `ric_sync_status` MODIFY COLUMN `sync_status` VARCHAR(48) NOT NULL DEFAULT 'pending' COMMENT 'synced, pending, failed, deleted, orphaned';
ALTER TABLE `rights_derivative_rule` MODIFY COLUMN `rule_type` VARCHAR(69) NOT NULL COMMENT 'watermark, redaction, resize, format_conversion, metadata_strip';
ALTER TABLE `rights_derivative_rule` MODIFY COLUMN `watermark_position` VARCHAR(65) DEFAULT 'bottom_right' COMMENT 'center, top_left, top_right, bottom_left, bottom_right, tile';
ALTER TABLE `rights_embargo` MODIFY COLUMN `embargo_type` VARCHAR(49) NOT NULL DEFAULT 'full' COMMENT 'full, metadata_only, digital_only, partial';
ALTER TABLE `rights_embargo` MODIFY COLUMN `reason` VARCHAR(95) NOT NULL COMMENT 'donor_restriction, copyright, privacy, legal, commercial, research, cultural, security, other';
ALTER TABLE `rights_embargo` MODIFY COLUMN `status` VARCHAR(48) DEFAULT 'active' COMMENT 'active, pending, lifted, expired, extended';
ALTER TABLE `rights_embargo_log` MODIFY COLUMN `action` VARCHAR(74) NOT NULL COMMENT 'created, extended, lifted, reviewed, notification_sent, auto_released';
ALTER TABLE `rights_grant` MODIFY COLUMN `act` VARCHAR(105) NOT NULL COMMENT 'render, disseminate, replicate, migrate, modify, delete, print, use, publish, excerpt, annotate, move, sell';
ALTER TABLE `rights_grant` MODIFY COLUMN `restriction` VARCHAR(36) NOT NULL DEFAULT 'allow' COMMENT 'allow, disallow, conditional';
ALTER TABLE `rights_orphan_search_step` MODIFY COLUMN `source_type` VARCHAR(93) NOT NULL COMMENT 'database, registry, publisher, author_society, archive, library, internet, newspaper, other';
ALTER TABLE `rights_orphan_work` MODIFY COLUMN `status` VARCHAR(61) DEFAULT 'in_progress' COMMENT 'in_progress, completed, rights_holder_found, abandoned';
ALTER TABLE `rights_orphan_work` MODIFY COLUMN `work_type` VARCHAR(115) NOT NULL COMMENT 'literary, dramatic, musical, artistic, film, sound_recording, broadcast, typographical, database, photograph, other';
ALTER TABLE `rights_record` MODIFY COLUMN `basis` VARCHAR(54) NOT NULL DEFAULT 'copyright' COMMENT 'copyright, license, statute, donor, policy, other';
ALTER TABLE `rights_record` MODIFY COLUMN `copyright_status` VARCHAR(43) DEFAULT 'unknown' COMMENT 'copyrighted, public_domain, unknown';
ALTER TABLE `rights_statement` MODIFY COLUMN `category` VARCHAR(41) NOT NULL COMMENT 'in-copyright, no-copyright, other';
ALTER TABLE `rights_territory` MODIFY COLUMN `territory_type` VARCHAR(25) NOT NULL DEFAULT 'include' COMMENT 'include, exclude';
ALTER TABLE `rights_tk_label` MODIFY COLUMN `category` VARCHAR(27) NOT NULL DEFAULT 'tk' COMMENT 'tk, bc, attribution';
ALTER TABLE `saved_search` MODIFY COLUMN `notification_frequency` VARCHAR(30) DEFAULT 'weekly' COMMENT 'daily, weekly, monthly';
ALTER TABLE `security_access_request` MODIFY COLUMN `priority` VARCHAR(33) DEFAULT 'normal' COMMENT 'normal, urgent, immediate';
ALTER TABLE `security_access_request` MODIFY COLUMN `request_type` VARCHAR(74) NOT NULL COMMENT 'view, download, print, clearance_upgrade, compartment_access, renewal';
ALTER TABLE `security_access_request` MODIFY COLUMN `status` VARCHAR(51) DEFAULT 'pending' COMMENT 'pending, approved, denied, expired, cancelled';
ALTER TABLE `security_clearance_history` MODIFY COLUMN `action` VARCHAR(86) NOT NULL COMMENT 'granted, upgraded, downgraded, revoked, renewed, expired, 2fa_enabled, 2fa_disabled';
ALTER TABLE `security_declassification_schedule` MODIFY COLUMN `trigger_type` VARCHAR(30) NOT NULL DEFAULT 'date' COMMENT 'date, event, retention';
ALTER TABLE `security_watermark_log` MODIFY COLUMN `watermark_type` VARCHAR(32) NOT NULL DEFAULT 'visible' COMMENT 'visible, invisible, both';
ALTER TABLE `semantic_synonym` MODIFY COLUMN `relation_type` VARCHAR(50) DEFAULT 'synonym' COMMENT 'synonym, broader, narrower, related, use_for';
ALTER TABLE `service_monitor_log` MODIFY COLUMN `event_type` VARCHAR(37) NOT NULL DEFAULT 'info' COMMENT 'down, warning, recovered, info';
ALTER TABLE `spectrum_approval` MODIFY COLUMN `status` VARCHAR(35) DEFAULT 'pending' COMMENT 'pending, approved, rejected';
ALTER TABLE `spectrum_condition_photo` MODIFY COLUMN `photo_type` VARCHAR(50) NOT NULL DEFAULT 'detail' COMMENT 'before, after, detail, damage, overall, other';
ALTER TABLE `spectrum_condition_photos` MODIFY COLUMN `category` VARCHAR(54) DEFAULT 'overall' COMMENT 'overall, detail, damage, before, after, reference';
ALTER TABLE `spectrum_condition_template_field` MODIFY COLUMN `field_type` VARCHAR(76) NOT NULL COMMENT 'text, textarea, select, multiselect, checkbox, radio, rating, date, number';
ALTER TABLE `spectrum_loan_agreements` MODIFY COLUMN `loan_type` VARCHAR(20) NOT NULL COMMENT 'in, out';
ALTER TABLE `tiff_pdf_merge_file` MODIFY COLUMN `status` VARCHAR(46) DEFAULT 'uploaded' COMMENT 'uploaded, processing, processed, failed';
ALTER TABLE `tiff_pdf_merge_job` MODIFY COLUMN `orientation` VARCHAR(33) DEFAULT 'auto' COMMENT 'auto, portrait, landscape';
ALTER TABLE `tiff_pdf_merge_job` MODIFY COLUMN `page_size` VARCHAR(33) DEFAULT 'auto' COMMENT 'auto, a4, letter, legal, a3';
ALTER TABLE `tiff_pdf_merge_job` MODIFY COLUMN `pdf_standard` VARCHAR(37) DEFAULT 'pdfa-2b' COMMENT 'pdf, pdfa-1b, pdfa-2b, pdfa-3b';
ALTER TABLE `tiff_pdf_merge_job` MODIFY COLUMN `status` VARCHAR(52) DEFAULT 'pending' COMMENT 'pending, queued, processing, completed, failed';
ALTER TABLE `tiff_pdf_settings` MODIFY COLUMN `setting_type` VARCHAR(37) DEFAULT 'string' COMMENT 'string, integer, boolean, json';
ALTER TABLE `triposr_jobs` MODIFY COLUMN `output_format` VARCHAR(20) DEFAULT 'glb' COMMENT 'glb, obj';
ALTER TABLE `triposr_jobs` MODIFY COLUMN `processing_mode` VARCHAR(22) DEFAULT 'local' COMMENT 'local, remote';
ALTER TABLE `triposr_jobs` MODIFY COLUMN `status` VARCHAR(45) DEFAULT 'pending' COMMENT 'pending, processing, completed, failed';
ALTER TABLE `user_browse_settings` MODIFY COLUMN `default_sort_direction` VARCHAR(20) DEFAULT 'desc' COMMENT 'asc, desc';
ALTER TABLE `user_display_preference` MODIFY COLUMN `card_size` VARCHAR(28) DEFAULT 'medium' COMMENT 'small, medium, large';
ALTER TABLE `user_display_preference` MODIFY COLUMN `sort_direction` VARCHAR(20) DEFAULT 'desc' COMMENT 'asc, desc';
ALTER TABLE `user_security_clearance_log` MODIFY COLUMN `action` VARCHAR(41) NOT NULL COMMENT 'granted, revoked, updated, expired';
ALTER TABLE `viewer_3d_settings` MODIFY COLUMN `setting_type` VARCHAR(37) DEFAULT 'string' COMMENT 'string, integer, boolean, json';

SELECT COUNT(*) AS remaining_enums FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND DATA_TYPE = 'enum';
