all:
  # AtoM Heratio configuration
  # Generated by atom-heratio package installer

  # Site settings
  siteTitle: "{{SITE_TITLE}}"
  siteDescription: "{{SITE_DESCRIPTION}}"
  siteBaseUrl: "{{SITE_URL}}"

  # Elasticsearch
  search_host: "{{ES_HOST}}"

  # Upload limits
  upload_limit: -1

  # Default culture
  i18n:
    languages:
      - en

  # Content Security Policy
  csp:
    enabled: true
    report_only: false
    default-src: "'self'"
    script-src: "'self' https://cdn.jsdelivr.net https://d3js.org"
    style-src: "'self' 'unsafe-hashes' https://cdn.jsdelivr.net https://fonts.googleapis.com"
    img-src: "'self' data: blob:"
    font-src: "'self' https://cdn.jsdelivr.net https://fonts.gstatic.com"
    connect-src: "'self'"
    frame-src: "'self'"
    object-src: "'none'"
    base-uri: "'self'"
