<?php
// AtoM database configuration
// Generated by atom-heratio package installer

return [
    'all' => [
        'propel' => [
            'class' => 'sfPropelDatabase',
            'param' => [
                'encoding' => 'utf8mb4',
                'persistent' => true,
                'pooling' => true,
                'dsn' => 'mysql:host={{DB_HOST}};dbname={{DB_NAME}};charset=utf8mb4',
                'username' => '{{DB_USER}}',
                'password' => '{{DB_PASS}}',
            ],
        ],
    ],
];
